-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 435,
  ["line_length"] = 16,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {-0.5 / 64, -10.5 / 64},
  ["sprite_count"] = 256,
  ["width"] = 451,
}
