-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 390,
  ["line_length"] = 13,
  ["lines_per_file"] = 20,
  ["scale"] = 0.5,
  ["shift"] = {82 / 64, 51 / 64},
  ["sprite_count"] = 256,
  ["width"] = 600,
}
