-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 363,
  ["line_length"] = 15,
  ["lines_per_file"] = 18,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, 4.5 / 64},
  ["sprite_count"] = 256,
  ["width"] = 426,
}
