-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 2,
  ["height"] = 551,
  ["line_length"] = 12,
  ["lines_per_file"] = 14,
  ["scale"] = 0.5,
  ["shift"] = {-0.5 / 64, -86.5 / 64},
  ["sprite_count"] = 256,
  ["width"] = 665,
}
