-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 2,
  ["height"] = 497,
  ["line_length"] = 10,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {111.5 / 64, -4.5 / 64},
  ["sprite_count"] = 256,
  ["width"] = 771,
}
